#!/usr/bin/env php
<?php
require \implode( DIRECTORY_SEPARATOR, [ __DIR__, 'vendor', 'autoload.php' ] );

use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;
use Console\Command\MoleculeTransfer;

// Bind a command
$commands = [

    MoleculeTransfer::class,

];

$container = new Container();
$events    = new Dispatcher( $container );
$artisan   = new Application( $container, $events, '0.0.0.1' );
$artisan->setName( 'Console KnishIO Client PHP' );
\array_walk($commands, static function ( $command ) use ( $artisan ) { $artisan->resolve( $command ); });
$artisan->run();