<?php

namespace WishKnish\KnishIO\Client\Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use WishKnish\KnishIO\Client\Libraries\Crypto;
use WishKnish\KnishIO\Client\Libraries\Crypto\Shake256;
use WishKnish\KnishIO\Client\Wallet;

/**
 * Cross-platform canonical test vectors — verifies PHP SDK against
 * the shared cross-platform-test-vectors.json (Rust reference implementation).
 */
class CrossPlatformVectorsTest extends TestCase {

  private array $vectors;

  protected function setUp (): void {
    parent::setUp();
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $this->vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
  }

  #[DataProvider('shake256Provider')]
  public function testShake256 ( string $name, string $input, int $outputLength, string $expected ): void {
    // Shake256::hash returns raw bytes; outputLength in the vector file is in bytes
    $result = bin2hex( Shake256::hash( $input, $outputLength ) );
    $this->assertEquals( $expected, $result, "SHAKE256 mismatch for vector: $name" );
  }

  public static function shake256Provider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'shake256' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'input' ],
        $test[ 'outputLength' ],
        $test[ 'expected' ],
      ];
    }
    return $cases;
  }

  #[DataProvider('bundleHashProvider')]
  public function testBundleHash ( string $name, string $secret, string $expected ): void {
    $result = Crypto::generateBundleHash( $secret );
    $this->assertEquals( $expected, $result, "Bundle hash mismatch for vector: $name" );
  }

  public static function bundleHashProvider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'bundle_hash' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'secret' ],
        $test[ 'expected' ],
      ];
    }
    return $cases;
  }

  #[DataProvider('walletProvider')]
  public function testWalletAddress ( string $name, string $secret, string $token, string $position, string $expectedBundle, string $expectedAddress ): void {
    // Bundle hash must match
    $bundle = Crypto::generateBundleHash( $secret );
    $this->assertEquals( $expectedBundle, $bundle, "Bundle hash mismatch for wallet: $name" );

    // Create wallet with secret, token, and explicit position
    $wallet = new Wallet( $secret, $token, $position );
    $this->assertEquals( $expectedAddress, $wallet->address, "Wallet address mismatch for wallet: $name" );
  }

  public static function walletProvider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'wallet_generation' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'secret' ],
        $test[ 'token' ],
        $test[ 'position' ],
        $test[ 'expectedBundle' ],
        $test[ 'expectedAddress' ],
      ];
    }
    return $cases;
  }

  // ML-KEM768 keygen-from-seed is deterministic (FIPS-203) → byte-frozen pubkey, like a SHAKE vector.
  public function testMlkem768Keygen (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ], mlKemParameterSet: 768 );
    $this->assertEquals( $v[ 'expectedPubkey' ], $wallet->pubkey, 'ML-KEM768 keygen pubkey mismatch' );
  }

  // Decapsulation + AES-256-GCM decrypt is deterministic → the frozen {cipherText, encryptedMessage}
  // (generated by the JS reference) must decrypt to the canonical plaintext via PHP's ML-KEM path.
  public function testMlkem768Decrypt (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'decrypt' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ], mlKemParameterSet: 768 );
    $plaintext = $wallet->decryptMessageML( [
      'cipherText' => $v[ 'cipherText' ],
      'encryptedMessage' => $v[ 'encryptedMessage' ],
    ] );
    $this->assertEquals( $v[ 'expectedPlaintext' ], $plaintext, 'ML-KEM768 decrypt plaintext mismatch' );
  }

  // PQ-transport hardening: a stale/non-PQ validator advertises a ~48-byte `key`; encryptMessageML
  // must fail with an actionable error, not a cryptic bridge crash.
  public function testMlkem768EncryptRejectsNon1184Key (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ], mlKemParameterSet: 768 );
    $shortKey = base64_encode( str_repeat( "\0", 48 ) );
    $this->expectException( \WishKnish\KnishIO\Client\Exception\CryptoException::class );
    $this->expectExceptionMessageMatches( '/expected 1184 \(ML-KEM-768\)/' );
    $wallet->encryptMessageML( [ 'q' => 1 ], $shortKey );
  }

  public function testMlkem1024Keygen (): void {
    $v = $this->vectors[ 'mlkem1024' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $this->assertEquals( $v[ 'expectedPubkey' ], $wallet->pubkey, 'ML-KEM1024 keygen pubkey mismatch' );
  }

  public function testMlkem1024Decrypt (): void {
    $v = $this->vectors[ 'mlkem1024' ][ 'decrypt' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $plaintext = $wallet->decryptMessageML( [
      'cipherText' => $v[ 'cipherText' ],
      'encryptedMessage' => $v[ 'encryptedMessage' ],
    ] );
    $this->assertEquals( $v[ 'expectedPlaintext' ], $plaintext, 'ML-KEM1024 decrypt plaintext mismatch' );
  }

  public function testMlkem1024EncryptRejectsNon1568Key (): void {
    $v = $this->vectors[ 'mlkem1024' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $shortKey = base64_encode( str_repeat( "\0", 48 ) );
    $this->expectException( \WishKnish\KnishIO\Client\Exception\CryptoException::class );
    $this->expectExceptionMessageMatches( '/expected 1568 \(ML-KEM-1024\)/' );
    $wallet->encryptMessageML( [ 'q' => 1 ], $shortKey );
  }

  // Classical NaCl (X25519 scalarmult_base + crypto_box/secretbox + sealed-box),
  // byte-frozen against the reference tweetnacl. ext-sodium (libsodium) must
  // reproduce these byte-for-byte, proving classical cross-SDK parity.
  public function testNaClVectors (): void {
    $v = $this->vectors[ 'nacl' ];

    // X25519 scalarmult_base: 32-byte secret → 32-byte public.
    foreach ( $v[ 'scalarMultBase' ] as $c ) {
      $pk = sodium_crypto_scalarmult_base( hex2bin( $c[ 'secretKeyHex' ] ) );
      $this->assertEquals( $c[ 'expectedPublicKey' ], base64_encode( $pk ), 'X25519 scalarmult_base mismatch' );
    }

    // crypto_box with a fixed nonce → [MAC(16)‖ct], deterministic.
    $cb = $v[ 'cryptoBox' ];
    $boxed = sodium_crypto_box(
      $cb[ 'plaintext' ],
      base64_decode( $cb[ 'nonce' ] ),
      sodium_crypto_box_keypair_from_secretkey_and_publickey(
        hex2bin( $cb[ 'senderSecretKeyHex' ] ),
        base64_decode( $cb[ 'recipientPublicKey' ] )
      )
    );
    $this->assertEquals( $cb[ 'expectedBox' ], base64_encode( $boxed ), 'crypto_box ciphertext mismatch' );

    // sealed-box: decrypt a frozen blob (encrypt is non-deterministic — random ephemeral).
    $sb = $v[ 'sealedBox' ];
    $keypair = sodium_crypto_box_keypair_from_secretkey_and_publickey(
      hex2bin( $sb[ 'recipientSecretKeyHex' ] ),
      base64_decode( $sb[ 'recipientPublicKey' ] )
    );
    $pt = sodium_crypto_box_seal_open( base64_decode( $sb[ 'sealed' ] ), $keypair );
    $this->assertEquals( $sb[ 'expectedPlaintext' ], $pt, 'sealed-box open mismatch' );
  }
}
