<?php

namespace WishKnish\KnishIO\Client\Tests;

use WishKnish\KnishIO\Client\Libraries\Crypto;
use WishKnish\KnishIO\Client\Libraries\Crypto\Shake256;
use WishKnish\KnishIO\Client\Wallet;

/**
 * Cross-platform canonical test vectors — verifies PHP SDK against
 * the shared cross-platform-test-vectors.json (Rust reference implementation).
 */
class CrossPlatformVectorsTest extends TestCase {

  private array $vectors;

  protected function setUp (): void {
    parent::setUp();
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $this->vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
  }

  /**
   * @dataProvider shake256Provider
   */
  public function testShake256 ( string $name, string $input, int $outputLength, string $expected ): void {
    // Shake256::hash returns raw bytes; outputLength in the vector file is in bytes
    $result = bin2hex( Shake256::hash( $input, $outputLength ) );
    $this->assertEquals( $expected, $result, "SHAKE256 mismatch for vector: $name" );
  }

  public function shake256Provider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'shake256' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'input' ],
        $test[ 'outputLength' ],
        $test[ 'expected' ],
      ];
    }
    return $cases;
  }

  /**
   * @dataProvider bundleHashProvider
   */
  public function testBundleHash ( string $name, string $secret, string $expected ): void {
    $result = Crypto::generateBundleHash( $secret );
    $this->assertEquals( $expected, $result, "Bundle hash mismatch for vector: $name" );
  }

  public function bundleHashProvider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'bundle_hash' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'secret' ],
        $test[ 'expected' ],
      ];
    }
    return $cases;
  }

  /**
   * @dataProvider walletProvider
   */
  public function testWalletAddress ( string $name, string $secret, string $token, string $position, string $expectedBundle, string $expectedAddress ): void {
    // Bundle hash must match
    $bundle = Crypto::generateBundleHash( $secret );
    $this->assertEquals( $expectedBundle, $bundle, "Bundle hash mismatch for wallet: $name" );

    // Create wallet with secret, token, and explicit position
    $wallet = new Wallet( $secret, $token, $position );
    $this->assertEquals( $expectedAddress, $wallet->address, "Wallet address mismatch for wallet: $name" );
  }

  public function walletProvider (): array {
    $path = __DIR__ . '/fixtures/cross-platform-test-vectors.json';
    $vectors = json_decode( file_get_contents( $path ), true )[ 'vectors' ];
    $cases = [];
    foreach ( $vectors[ 'wallet_generation' ][ 'tests' ] as $test ) {
      $cases[ $test[ 'name' ] ] = [
        $test[ 'name' ],
        $test[ 'secret' ],
        $test[ 'token' ],
        $test[ 'position' ],
        $test[ 'expectedBundle' ],
        $test[ 'expectedAddress' ],
      ];
    }
    return $cases;
  }

  // ML-KEM768 keygen-from-seed is deterministic (FIPS-203) → byte-frozen pubkey, like a SHAKE vector.
  public function testMlkem768Keygen (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $this->assertEquals( $v[ 'expectedPubkey' ], $wallet->pubkey, 'ML-KEM768 keygen pubkey mismatch' );
  }

  // Decapsulation + AES-256-GCM decrypt is deterministic → the frozen {cipherText, encryptedMessage}
  // (generated by the JS reference) must decrypt to the canonical plaintext via PHP's ML-KEM path.
  public function testMlkem768Decrypt (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'decrypt' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $plaintext = $wallet->decryptMessageML768( [
      'cipherText' => $v[ 'cipherText' ],
      'encryptedMessage' => $v[ 'encryptedMessage' ],
    ] );
    $this->assertEquals( $v[ 'expectedPlaintext' ], $plaintext, 'ML-KEM768 decrypt plaintext mismatch' );
  }

  // PQ-transport hardening: a stale/non-PQ validator advertises a ~48-byte `key`; encryptMessageML768
  // must fail with an actionable error, not a cryptic bridge crash.
  public function testMlkem768EncryptRejectsNon1184Key (): void {
    $v = $this->vectors[ 'mlkem768' ][ 'keygen' ];
    $wallet = new Wallet( $v[ 'secret' ], $v[ 'token' ], $v[ 'position' ] );
    $shortKey = base64_encode( str_repeat( "\0", 48 ) );
    $this->expectException( \WishKnish\KnishIO\Client\Exception\CryptoException::class );
    $this->expectExceptionMessageMatches( '/expected 1184 \(ML-KEM-768\)/' );
    $wallet->encryptMessageML768( [ 'q' => 1 ], $shortKey );
  }
}
